-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 09:59:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotroca_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotroca_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotroca_bd` ;
USE `bibliotroca_bd` ;

-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `senha` VARCHAR(255) NULL,
  `icone` VARCHAR(255) NOT NULL DEFAULT 'default.png',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO `bibliotroca_bd`.`usuarios` 
  SET
    uuid = "0661993e-7ae8-4146-8602-403f5edb92ea",
    usuario = "admin",   
    nome = "Administrador",
    email = "admin@admin.com",
    telefone = "(99) 99999-9999",
    senha = "$2y$10$NA2as4khHjPOlIe/ocscHOmtFQstBd.tiUqYKHw08EnHxDfC//BNK",
    ativo = 1
;

-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(45) NOT NULL DEFAULT 'S/N',
  `complemento` VARCHAR(255) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_endeecos_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_endeecos_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bibliotroca_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `paginas` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  `descricao` TEXT(1000) NULL,
  `estado` ENUM('novo', 'seminovo', 'antigo') NOT NULL,
  `imagem` VARCHAR(255) NOT NULL DEFAULT 'default.png',
  `usuarios_id` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `categorias_id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_livros_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_livros_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_livros_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `bibliotroca_bd`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bibliotroca_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`trocas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`trocas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `livros_id` INT NOT NULL,
  `dono_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `situacao` ENUM('aceita', 'em andamento', 'rejeitado') NOT NULL DEFAULT 'em andamento',
  `dono_confirmacao` TINYINT(1) NOT NULL DEFAULT 0,
  `usuario_confirmacao` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `livros_id`, `dono_id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_trocas_livros1_idx` (`livros_id` ASC) VISIBLE,
  INDEX `fk_trocas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_trocas_usuarios2_idx` (`dono_id` ASC) VISIBLE,
  UNIQUE INDEX `livros_id_UNIQUE` (`livros_id` ASC) VISIBLE,
  UNIQUE INDEX `dono_id_UNIQUE` (`dono_id` ASC) VISIBLE,
  UNIQUE INDEX `usuarios_id_UNIQUE` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_trocas_livros1`
    FOREIGN KEY (`livros_id`)
    REFERENCES `bibliotroca_bd`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trocas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bibliotroca_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trocas_usuarios2`
    FOREIGN KEY (`dono_id`)
    REFERENCES `bibliotroca_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotroca_bd`.`recuperar_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotroca_bd`.`recuperar_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `codigo` INT(6) NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_recuperar_senha_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_recuperar_senha_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bibliotroca_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
